### ISSUE TITLE
Gets Stuck In A Loop

### ISSUE THREAD

**Issue by jordan4ibanez** [dkorpel/ctod#16]
So I let this run overnight chewing through https://codeberg.org/drummyfish/tinyphysicsengine/src/branch/master/tinyphysicsengine.h
it never finished

Seems like the Node accumulator gets caught in an infinite loop finding nodes.

I have no idea what would cause this, maybe the file is too long?

**Comment by dkorpel** [comment]
There's two things going on. One, this macro part with operators as arguments:
```C
    assignVec(j1,0,x,+)
    assignVec(j1,1,y,+)
    assignVec(j1,2,z,+)
    assignVec(j2,0,x,-)
    assignVec(j2,1,y,-)
    assignVec(j2,2,z,-)
```
Creates a very deep, complex parse tree because of errors. 

Two: I accidentally introduced exponential time complexity by calling `findChildren()` twice on each node :see_no_evil:

**Comment by dkorpel** [comment]
Fixed by https://github.com/dkorpel/ctod/commit/fe02732b858993727f277f27522ffd74c9136612

It now translates that file in 200 ms for me. ctod is not doing anything that's supposed to be computationally expensive, if it takes longer than a second it's probably because of an accidental time complexity blow up.

**Comment by jordan4ibanez** [comment]
Very nice work. Great job!
