### ISSUE TITLE
Weird translation of extern "C" closing guard

### ISSUE THREAD

**Issue by schveiguy** [dkorpel/ctod#2]
This:

```c
#ifdef __cplusplus
}
#endif
```

translates to this:
```d
version(none) {
}
}
```

Which doesn't work... The initial header translates to:
```d
#ifdef __cplusplus
extern "C" {
//! #endif
```
Which isn't great, but at least is obviously wrong, and it still has the `__cplusplus` statement there instead of the unrelated `version(none)`

**Comment by schveiguy** [comment]
Don't worry about working on all these issues for my sake, I'm perfectly happy to work with what the current ctod gives me. I'm just filing issues as I see them.

**Comment by dkorpel** [comment]
So there's two things going on here:
- the `__cplusplus` version is translated to `none` because we're only translating C, not C++
- tree-sitter is parsing C preprocessor directives as if they make a well-formed AST, so it doesn't handle an `#ifdef` inserting partial code very well. 

I put this code in the [tree-sitter playground](https://tree-sitter.github.io/tree-sitter/playground):
```C
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif
```

It thinks that the first #endif is a preprocessor call similar to `#pragma`, that the second `#endif` matches the first `#ifdef`, and that the second #ifdef is missing an #endif.

I don't think there's much I can do with the broken AST tree-sitter gives me here. It's probably best to preprocess a bit myself and remove `#ifdef __cplusplus` blocks manually before parsing with tree-sitter, but I'll hold off on that one for now.

**Comment by schveiguy** [comment]
Yeah c++ guards are pretty common, so an automated solution would be ideal. I’ll try something to see if I can fool it.

**Comment by dkorpel** [comment]
Fixed by https://github.com/dkorpel/ctod/commit/d60f60983b075f6b4016cc74ba19d0da62e91226
