### ISSUE TITLE
Fails to translate many C symbols in newer version of `raygui.h`, while it succeeded before.

### ISSUE THREAD

**Issue by LiamM32** [dkorpel/ctod#37]
Try going to the [raygui](https://github.com/raysan5/raygui/tree/3.5) repository and try translating `src/raygui.h` to D using CtoD. First try translating [version  3.5 of this file](https://github.com/raysan5/raygui/blob/3.5/src/raygui.h) and then try translating [version 4.0](https://github.com/raysan5/raygui/blob/4.0/src/raygui.h).

Between these two revisions of this file, CtoD loses much competence as a translator. Many things that get properly translated for version 3.5 are left in C syntax for version 4.0 of this file.
- No longer changing `const char *` to `const(char)*`
- No longer changing `(float)` to `cast(float)`
- No longer changing `#if defined` to `version`
- Other cases of leaving in C preprocessor directives.
- No longer changing `NULL` to `null`

Perhaps there was something added to this file that CtoD tripped on, making CtoD think it's reading a comment or something when it's not.

I don't know how this program works, but for those who do, this may be a good place to look for faults, since the older version of the file was processed much better.

**Comment by dkorpel** [comment]
Thanks for reporting. These things can happen when tree-sitter-c (the C parser ctod uses) stumbles on a C Macro introducing new syntax, producing error nodes. While it's good at recovering from these, the error nodes itself will get a poor translation.

In raygui, the problematic parts are:

```C
#ifdef __cplusplus
    #define RAYGUI_CLITERAL(name) name
#else
    #define RAYGUI_CLITERAL(name) (name)
#endif

/// ...

GuiDrawRectangle(RAYGUI_CLITERAL(Rectangle){ ... });
```

This fails to parse as a struct initializer. Then there's the classic API macro:

```C
// Function specifiers in case library is build/used as a shared library (Windows)
// NOTE: Microsoft specifiers to tell compiler that symbols are imported/exported from a .dll
#if defined(_WIN32)
    #if defined(BUILD_LIBTYPE_SHARED)
        #define RAYGUIAPI __declspec(dllexport)     // We are building the library as a Win32 shared library (.dll)
    #elif defined(USE_LIBTYPE_SHARED)
        #define RAYGUIAPI __declspec(dllimport)     // We are using the library as a Win32 shared library (.dll)
    #endif
#endif

// Function specifiers definition
#ifndef RAYGUIAPI
    #define RAYGUIAPI       // Functions defined as 'extern' by default (implicit specifiers)
#endif
```
 
Which messes up the parsing of the return type, but ctod has a workaround for simple cases.

I have to think about the best way to solve this issue. Perhaps I can try to recognize 'wrapper' defines like `#define RAYGUI_CLITERAL(name) (name)` and preprocess them before parsing. In any case, ctod could print error locations to stderr, so the user at least knows where the troublesome parts are.

However, there seems to be a bit more going on, because I can't entirely reproduce this issue.

> Many things that get properly translated for version 3.5 are left in C syntax for version 4.0 of this file.

I don't see that much of a difference in mistranslations: In the translation of 4.0, the only instances of capitalized `NULL` are in actual comments, there's just one `(float)` missing the `cast` keyword following a `RAYGUI_CLITERAL` macro. And there's only 1 `#ifndef` token being left in the .d file. It sounds like you're finding a lot more than that, can you quantify the amount of errors. or show the translation you get?

**Comment by LiamM32** [comment]
I'm sorry, but I just tried it again, and I'm not finding nearly as many problems as yesterday. Yesterday I tried doing it twice, with many problems both times, but now I have edited the files, so I don't have anything for you. I don't know what I did differently between yesterday and today.

I tried it again today, and didn't find nearly as many instances of `const char *` as yesterday. I also didn't find numerous cases of `NULL` like yesterday.
