### ISSUE TITLE
Support for multiple files and remove unnessessary declarations

### ISSUE THREAD

**Issue by LiamM32** [dkorpel/ctod#39]
If you tell a C compiler to compile a single C file which includes another file through `#include`, than the included file will also be compiled, so long as all functions that are declared are defined. I believe that CToD should also do this in most cases. By default I recommend that it does this for files within the current working directory (and subdirectories) but ideally this would be configurable. When processing C files, it will typically make multiple D files, but not necessarily the same number.

It should also remove unnecessary declarations of functions to a single definition (unless if a separate declaration is necessary). In some cases, depending on some rule, the function definition in D will correspond to where it was declared in the C header file, but in other cases (such as when it's declared and defined in the same file) the definition will be used and the initial declaration removed.

These additions will bring this tool further in automating the process of converting C code to D.

**Comment by dkorpel** [comment]
Thanks for your suggestions. 

The test case for unnecessary declarations would be:
```C
void f(int);

// functions that may use f

void f(void) { }
```

Which should translate to:
```D
// functions that may use f

void f() { }
```

I think that's easy to do in a second pass.

About multiple files, I'm not sure it's in the scope and spirit of this tool. ctod was made to automate tedious C syntax to D syntax translation. It deliberately has a simple interface of 'input C code' => 'output D code' without the need to set include paths, specify C dialects, or other configuration options. It doesn't refactor, or turn C-isms into idiomatic D code.

Of course there is 'impedance mismatch' between C and D with the preprocessor: you're right that `#include` doesn't always do the same as `public import` and should technically embed included definitions into the translation unit, but another deliberate limitation of ctod is that it assumes 'sane' use of the preprocessor. Not because that's realistic (I wish 🥲) but because there's no end to the amount of work needed to translate all the possible uses of the preprocessor to D.

So I think that part is a WONTFIX for now.

**Comment by LiamM32** [comment]
Thank you.

Even though this tool was originally made for a rather limited use, I think it would be worthwhile to expand it's scope to make it a more complete translator from C to D, and eventually C++ to D once the C translation is more complete.

I don't think we need to take away it's ability to do what it currently does if we add new things through command options.

I have already started working on trying to make it do these things. I intend to put the translation to D in a second pass. However, it's pushing my programming abilities, as I'm not very experienced.

**Comment by dkorpel** [comment]
Unnecessary declarations are fixed:
https://github.com/dkorpel/ctod/blob/d8f5cdd4e04d4b627b0aeb6e118f25dc71d80d42/source/ctod/test.d#L907-L912

Regarding scope: With the rise of ImportC and AI based code tools, I'm not motivated to put effort into expanding this program myself; it's getting diminishing returns. I insist on the simple interface, and adding C++ would require swapping out the tree-sitter parser for the C++ one and reworking almost everything from the ground up since C++ is a lot more complex than C.

Anyone is free to fork this and build a bigger better tool, but this repository just houses my little C translator program. I hope you understand. :slightly_smiling_face:

**Comment by LiamM32** [comment]
> Anyone is free to fork this and build a bigger better tool, but this repository just houses my little C translator program. I hope you understand. 🙂

Alright. I might just do that. I have already thought about using neural networks for some steps of the process, though I don't know how to do that yet. It would still use programmed logic for much of it to ease the burden on the NN.

If I make a fork, I'm probably going to slightly alter the name of the program. May I use the same logo? The `dub.sdl` says this is licensed under BSL, but I don't know what that means for the logo.

**Comment by dkorpel** [comment]
> May I use the same logo? The `dub.sdl` says this is licensed under BSL, but I don't know what that means for the logo.

I wouldn't worry about that now, but if you do end up publishing it on dub, I'd prefer it if you alter the logo so you can tell the projects apart. For example give it a different color, or put a symbol on top of it.

**Comment by LiamM32** [comment]
Just out of curiosity, why does this program use structs and pointers as objects instead of classes? I have considered designing the new features in a way that uses class inheritance, but first I would like to know the reason why the program currently uses structs instead of classes. Is it so that it can have a C API?

**Comment by dkorpel** [comment]
Structs are my go-to aggregate type. I reach for them first, unless I need inheritance. It also makes compiling to WebAssembly easier (though my WASM object.d does have class support now).
