### ISSUE TITLE
using sizeof with multiplication causes confusion

### ISSUE THREAD

**Issue by schveiguy** [dkorpel/ctod#7]
Another weird one, I originally thought related to #4, but it happens without the `unsigned` attribute.

```c
void foo(void) {
    size_t a = sizeof(unsigned char) * 5;
    size_t b = sizeof(unsigned char);
    size_t c = sizeof(int) * 5;
    size_t d = sizeof(int);
}   
```
```d
void foo() {
    size_t a = sizeofcast(ubyte) * 5;
    size_t b = ubyte.sizeof;
    size_t c = sizeofcast(int) * 5;
    size_t d = int.sizeof;
}
```

`sizeof(...) * something` is used a lot in malloc calls, so this is an important one.

**Comment by dkorpel** [comment]
This one is tree-sitter's fault, because it parses `sizeof(int)*5` as a sizeof + cast + pointer dereference `sizeof ((int) *5)`. Or maybe it's C's fault for having such an ambiguous grammar.

I think I can recognize this specific pattern and work around it, but it may be unsolvable in the general case.

**Comment by schveiguy** [comment]
well, at least the thing results in a very greppable `sizeofcast` identifier 😂

**Comment by schveiguy** [comment]
Hm... regardless, it probably shouldn't do `sizeofcast` since this clearly isn't the intention.

**Comment by dkorpel** [comment]
Fixed by https://github.com/dkorpel/ctod/commit/ccbe1eca5373aac282317321495bb74048fc5387, if you find new patterns it messed up please re-open / file a new issue.
